// FE/Apt-side eChallengeTypes enum (Flash UI challenge types; wire int to name).
namespace Arcadia.Hosting.Lobby.Protocol
{
    public static class Sk8XmlChallengeType
    {
        public static string? ToName(int type) => type switch
        {
            0  => "Tutorial",
            1  => "PointContest",
            2  => "Demo",
            3  => "Risk",
            4  => "SKATE",
            5  => "SKATE_Multi",
            6  => "Photo",
            7  => "Film",
            8  => "BestTrick",
            9  => "OwnTheSpot",
            10 => "Slalom",
            11 => "Slide",
            12 => "Lap",
            13 => "Gate",
            14 => "Favour",
            15 => "Jam",
            16 => "Crash",
            17 => "Security",
            18 => "Point2PointRace",
            19 => "DeathRace",
            20 => "SpotRace",
            21 => "LastManStanding",
            22 => "OnlineFreeSkate",
            23 => "Follow",
            24 => "TrainStation",
            25 => "SkateShop",
            26 => "MegaRamp",
            27 => "StreetSkating",
            28 => "Pro",
            29 => "Teleporter",
            30 => "Goto",
            31 => "HallOfMeat",
            32 => "1up",
            33 => "HallOfMeat_SP",
            34 => "Service",
            35 => "CreateASpot",
            36 => "CreateASpot_Setup",
            37 => "AnywherePhoto",
            38 => "SpotPhoto",
            39 => "AnywhereFilm",
            40 => "SpotFilm",
            41 => "FriendFilm",
            42 => "OnlineFreeSkateActivity",
            43 => "Dummy",
            44 => "Flow",
            45 => "Property",
            46 => "PickaProFilm",
            47 => "PickaProPhoto",
            48 => "TeamFilm",
            49 => "TeamPhoto",
            50 => "Landmark",
            _ => null,
        };
    }
}
